Vagrant.configure("2") do |config|

  ## OS: Ubuntu 14.04 LTS 64bit
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  ## Ports forwarded: http, jenkins and sonar
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "forwarded_port", guest: 9000, host: 19000

  ## Synced folders
  config.vm.synced_folder "../..", "/home/vagrant/apps"

  ## Provisioner: salt
  config.vm.provision :salt do |salt|

    salt.minion_config = "minion"
    salt.minion_key = "key.pem"
    salt.minion_pub = "key.pub"
    salt.run_highstate = true

  end
end
