Vagrant.configure("2") do |config|

  ## OS: Ubuntu 14.04 LTS 64bit
  config.vm.box = "ubuntu/trusty64"

  ## Ports forwarded: http
  config.vm.network "forwarded_port", guest: 80, host: 10080

  ## Synced folders
  config.vm.synced_folder "../..", "/home/vagrant/repos"

  ## Provisioner: salt
  config.vm.provision :salt do |salt|

    salt.minion_config = "minion"
    salt.minion_key = "key.pem"
    salt.minion_pub = "key.pub"
    salt.run_highstate = true

  end
end
